apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-406
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '4.0.6'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: default
      interval: 1m
  values:
    replicaCount: 1
