apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: auto-deploys
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/juozasg/dev-driven-auto-deploys.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: auto-deploys
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./deploy/stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: auto-deploys
    namespace: flux-system
  targetNamespace: default

